stock const char g_sDefaultTurnedModel[][] = {
	"models/nmr_zombie/badass_infected.mdl",
	"models/nmr_zombie/bateman_infected.mdl",
	"models/nmr_zombie/butcher_infected.mdl",
	"models/nmr_zombie/hunter_infected.mdl",
	"models/nmr_zombie/jive_infected.mdl",
	"models/nmr_zombie/molotov_infected.mdl",
	"models/nmr_zombie/roje_infected.mdl",
	"models/nmr_zombie/wally_infected.mdl"
};

// could be found via CBaseEntity *CNMRiH_ZombieRunner::pModels
stock const char g_sDefaultZombieModel[][] = {
    "models/nmr_zombie/berny.mdl",
	"models/nmr_zombie/herby.mdl",
	"models/nmr_zombie/jogger.mdl",
	"models/nmr_zombie/casual_02.mdl",
	"models/nmr_zombie/maxx.mdl",
	"models/nmr_zombie/officezom.mdl",
	"models/nmr_zombie/julie.mdl",
	"models/nmr_zombie/tammy.mdl",
	"models/nmr_zombie/national_guard.mdl"
};

stock const char g_sDefaultViewModel[][] = {
    "models/arms/c_badass_arms.mdl",
	"models/arms/c_bateman_arms.mdl",
	"models/arms/c_butcher_arms.mdl",
	"models/arms/c_hunter_arms.mdl",
	"models/arms/c_jive_arms.mdl",
	"models/arms/c_molotov_arms.mdl",
	"models/arms/c_roje_arms.mdl",
	"models/arms/c_wally_arms.mdl"
}